---
- name: Create a Docker Compose Host for testing
  hosts: localhost
  gather_facts: False
  vars:
    key_name: generic-cloud-wk
    instance_type: m4.large
    security_group: ansible
    image: ami-1d4e7a66
    region: us-east-1
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ key_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
#         vpc_subnet_id: subnet-29e63245
#         assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

- hosts: launched
  become: true
  remote_user: ubuntu
  gather_facts: false
  tasks:
    - name: Install Python Minimal
      raw: sudo apt update && sudo apt install -y python-minimal

    - name: Add Latest Repository for Ansible
      raw: sudo apt-add-repository ppa:ansible/ansible -y
   
    - name: Update Repo data
      raw: sudo apt-get update -y  

    - name: Install Ansible
      raw: sudo apt-get install -y ansible

    - name: Configure Local host for Ansible
      raw: sudo sh -c 'echo "localhost ansible_connection=local" >> /etc/ansible/hosts' 

    - name: Configure Log for Ansible
      raw: ssudo sh -c 'sed -i -e 's/#log_path/log_path/g' /etc/ansible/ansible.cfg' 

    - name: Pull AWX Foundation Artifacts
      git:
        repo: 'https://github.com/moffzilla/awx.git'
        dest: /home/ubuntu/awx-base

